Phase 1 Project-Team 3/Models/InventoryItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.SqlServer.Server;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phase_1_Project_Team_3.Models
{
    public class InventoryItem
    {

        public int Id { get; set; }
        public int CreatedByUserId { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }

    }
}

Phase 1 Project-Team 3/Controllers/InventoryItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using Phase_1_Project_Team_3.Models;

namespace Phase_1_Project_Team_3.Controllers
{
    public class InventoryItemsController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: InventoryItems
        [System.Web.Mvc.Authorize]
        public ActionResult Index()
        {
            return View(db.InventoryItems.ToList());
        }

        // GET: InventoryItems/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = await db.InventoryItems.FindAsync(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // GET: InventoryItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InventoryItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CreatedByUserId,Name,Quantity")] InventoryItem inventoryItem)
        {
            if (ModelState.IsValid)
            {
                inventoryItem.CreatedByUserId = (int)Session["CurrentUserId"];
                db.InventoryItems.Add(inventoryItem);
                await db.SaveChangesAsync();
                Hubs.InventoryHub.Send(inventoryItem);
                return RedirectToAction("Index");
            }

            return View(inventoryItem);
        }

        // GET: InventoryItems/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = await db.InventoryItems.FindAsync(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // POST: InventoryItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPut]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CreatedByUserId,Name,Quantity")] InventoryItem inventoryItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventoryItem).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(inventoryItem);
        }

        // GET: InventoryItems/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryItem inventoryItem = await db.InventoryItems.FindAsync(id);
            if (inventoryItem == null)
            {
                return HttpNotFound();
            }
            return View(inventoryItem);
        }

        // POST: InventoryItems/Delete/5
        [System.Web.Mvc.HttpPost, System.Web.Http.ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(InventoryItem inventoryItem)
        {
            db.InventoryItems.Remove(inventoryItem);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Phase 1 Project-Team 3/Views/InventoryItems/Create.cshtml
@model Phase_1_Project_Team_3.Models.InventoryItem

@{
    ViewBag.Title = "InvenotryItem";
}

<h2>Create Invenotry Item</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>

Phase 1 Project-Team 3/Views/InventoryItems/Delete.cshtml
@using Phase_1_Project_Team_3.Models
@model Phase_1_Project_Team_3.Models.InventoryItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedByUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedByUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger"/> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
        </div>        
    }
</div>
<script>
    var inventoryInfo =  [@Model.Id];
    localStorage.inventoryInfo = JSON.stringify(inventoryInfo);
    console.log(localStorage.inventoryInfo);
    $('form').submit(function (e) {
        e.preventDefault();

        $.ajax({
            url: '/api/Inventory/' + @Model.Id,
            type: 'DELETE',
            data: $('form').serializeArray(),
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            success: function(data) {
                window.location = '/InventoryItems';
            }
        });
        
    });


</script>

Phase 1 Project-Team 3/Views/InventoryItems/Details.cshtml
@model Phase_1_Project_Team_3.Models.InventoryItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>InventoryItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedByUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedByUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Phase 1 Project-Team 3/Views/InventoryItems/Edit.cshtml
@model Phase_1_Project_Team_3.Models.InventoryItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

       

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>


<script>


    $('form').submit(function(e) {
        e.preventDefault();

        $.ajax({
            url: '/api/Inventory',
            type: 'PUT',
            data: $('form').serializeArray(),
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            success: function(data) {
                window.location = '/InventoryItems';
            }
        });

    });


</script>

Phase 1 Project-Team 3/Views/InventoryItems/Index.cshtml
@model IEnumerable<Phase_1_Project_Team_3.Models.InventoryItem>

@{
    ViewBag.Title = "InventoryIndex";
}

<h2>Inventory Index</h2>

<p>
    @Html.ActionLink("Add New Item", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th></th>
    </tr>

    <tbody data-bind="foreach: items">
        <tr>

            <td data-bind="text: Name"></td>
            <td data-bind="text: Quantity"></td>

            <td>
                <a class="btn btn-success" data-bind="attr: { 'href': '@Url.Action("Edit", "InventoryItems")/' + Id}"><b>Edit</b></a>
                <a class="btn btn-success" data-bind="attr: { 'href': '@Url.Action("Delete", "InventoryItems")/' + Id}"><b>Delete
                    </b></a>
            </td>

        </tr>
    </tbody>
</table>

<script src="/signalr/hubs"></script>
<script src="~/Scripts/signalrRequests.js"></script>